[project]
name = "tfg-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gitpython>=3.1.45",
    "notebook>=7.4.7",
    "pandas>=2.3.3",
]
